name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # Skip lint for a while until we have a proper types
      #      - name: Lint
      #        run: yarn run lint

      - name: Test Project
        run: yarn test

      - name: Test Schematics
        run: yarn test:schematics

      - name: Build
        run: yarn build
